require("aerial").setup({
  icons = {
    Array = "󰅪",
    Boolean = "󰨙",
    Class = "󰠱",
    Constant = "󰏿",
    Constructor = "󰆧",
    Enum = "󰒻",
    EnumMember = "󰒻",
    Event = "󰉁",
    Field = "󰜢",
    File = "󰈙",
    Function = "󰊕",
    Interface = "󰕘",
    Key = "󰌋",
    Method = "󰆧",
    Module = "󰏗",
    Namespace = "󰌗",
    Number = "󰎠",
    Object = "󰅩",
    Operator = "󰆕",
    Package = "󰏖",
    Property = "󰜢",
    String = "󰀬",
    Struct = "󰌗",
    TypeParameter = "󰊄",
    Variable = "󰀫",
  },
})
